### ISSUE TITLE
peer review week 2

### ISSUE THREAD

**Issue by SharonV33** [sanneduinkerx/progressive-web-apps-2021#7]
## progressive web app
de app is downloadbaar en ziet er nice uit! Alleen werkt de offline versie een beetje raar ❔ ❔❔ Ik kan als ik offline ga nog steeds alles zoeken en inzien, ook als ik deze pagina's nog niet eerder bezocht heb. als het gepland is, super nice, anders misschien hier nog even naar kijken

## overall feedback
lekker bezig, project ziet er goed uit en werkt lekker! ik kan niets bedenken om nog op te merken verder 😄 
- [x] nog even de installatie in je readme uitleggen

**Comment by sanneduinkerx** [comment]
Thanks! Ik heb de readme nu aangepast :D en ik zal even kijken naar wat er fout gaat bij offline.
