### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by BVictorB** [sanneduinkerx/progressive-web-apps-2021#8]
## Repo
- Super nice dat je je readme & about stukje al hebt aangepast. Je readme is nog niet helemaal compleet maar ik heb er al het vertrouwen in dat je dat wel gaat fixen!
- Heel tof om te zien dat je het al hebt gedeployed op heroku, is ook erg nice met reviewen.
- Het is al erg compleet, je bent lekker bij!

## Code
- In zie in je index.js dat je een apikey hebt staan, er staat al een comment bij om hem te verstoppen maar nu staat ie al op GitHub :^), dus die blijft vooraltijd te vinden. Maakt natuurlijk niet zoveel uit maar zet hem ff in een .env bestandje en require hem dan weer in je index.js code. Dit kun je doen met de dotenv dependency. 
- Nice dat je al verschillende routes hebt die verschillende dingen renderen/doen, qua structuur en netheid is het wel nice als je deze routes misschien opsplitst in verschillende bestanden en een losse router hiervoor aanmaakt. Check ff mijn repo als je dit wilt doen, ik denk dat dat wel een mooi voorbeeld hiervan is.
- Je doet dit in een if statement op regel 41 `req.query.ArtistKeyword == undefined`, als je wilt dat iets wordt uitgevoerd als iets geen waarde heeft of false/null is, kun je ook dit doen: `!req.query.ArtistKeyword`, vind ik persoonlijk wat netter.
- Ohja en een goeie tip is om eigenlijk altijd === te gebruiken ipv ==, anders kun je ooit tegen hele vreemde dingen aanlopen, zie [=>](https://thisthat.dev/equality-operator-vs-strict-equality-operator)
- Je gebruikt de node-fetch dependency om je data binnen te halen, misschien kun je hier een functie van maken die je kunt importeren vanuit een ander bestand, dan kun je deze steeds opnieuw gebruiken als je hem nog op andere plekken nodig hebt. Dit zal er ongeveer hetzelfde uitzien als wat we voor WAFS hebben gedaan (alleen dan dus met node-fetch).
- Heel nice dat je al met url parameters hebt gewerkt! Netjes gedaan.
- Ook nice dat je al iets met serviceworkers hebt gedaan en een manifest.json bestand hebt gemaakt. Ik weet hier zelf niet zo veel over dus ik denk dat ik hier niet echt nuttige feedback op kan geven.

Super lekker bezig, ziet er allemaal top uit en je hebt echt een grote sprint gemaakt met express etc! Ga vooral zo door 🔥

**Comment by sanneduinkerx** [comment]
Dank je, voor de tips! Als ik tijd over heb zal ik de routes opsplitsen zelfde geldt voor de node-fetch. De rest heb ik toegepast :D
